version: '3.6'

services:

  esmain:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: esmain
    environment:
      - node.name=esmain
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/datamain:/usr/share/elasticsearch/data
      - ./es/logsmain:/usr/share/elasticsearch/logs
    ports:
      - 9203:9200
      - 9303:9300
    networks:
      - esnet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=esmain
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data01:/usr/share/elasticsearch/data
      - ./es/logs01:/usr/share/elasticsearch/logs
    networks:
      - esnet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=esmain
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data02:/usr/share/elasticsearch/data
      - ./es/logs02:/usr/share/elasticsearch/logs
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://esmain:9200
    ports:
      - 5603:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

networks:
  esnet:

